Добавляет класс argParser.
blessed2142/BlessedChat pull request #1
Opened 2023-12-13 19:01 UTC by blessed2142

2023-12-14 08:37 UTC, nekdfl requested changes
Оставил замечания. Они не критичные но посмотри на них

2023-12-14 08:37 UTC, nekdfl commented on Server/a.out
в репозиторий попал бинарный файл. Удали его из репозитория и поднастрой gitignore чтобы они туда не попадали. Компиляцию руками в файле проекта не запускай - всегда используй cmake + gitignore, чтобы не допускать такого в будущем.

2023-12-14 08:37 UTC, nekdfl commented on BlessedChat/src/Server.cpp
настрой include path в  cmake. Пути начинающиеся с ../ плохо заканчиваются.
Почему некоторые опции командной строки закомментированы? Они не рабочие? В PR надо стараться выкладывать рабочий код без комментированного. Комментированный код = мертвый код. 
В PR всегда должен быть рабочий код, даже если он написан не оптимально.

2023-12-14 08:37 UTC, nekdfl commented on components/arg_parser/CMakeLists.txt
не хватает include path

2023-12-14 08:37 UTC, nekdfl commented on CMakeLists.txt
не хватает linking directory path (каталоги в которых лежат библиотеки)

2023-12-16 10:20 UTC, blessed2142 commented on Server/a.out
Бинарный файл удален.

2023-12-16 10:24 UTC, blessed2142 commented on CMakeLists.txt
Это же главный cmake файл. Зачем здесь inking directory path не понимаю

2023-12-16 11:23 UTC, blessed2142 commented on components/arg_parser/CMakeLists.txt
Если имеется ввиду CMakeLists BlessedChat'a то добавил.

2023-12-16 11:27 UTC, blessed2142 commented on BlessedChat/src/Server.cpp
Include сделал. Некоторые опции закоментированы так как это просто тестовая оболочка. Сам метод вообще будет имлементирован в Application

2023-12-19 07:18 UTC, nekdfl approved these changes

2023-12-19 09:49 UTC, merged