Config impl
blessed2142/BlessedChat pull request #2
Opened 2023-12-18 20:02 UTC by blessed2142

2023-12-19 09:55 UTC, nekdfl requested changes
из критичного - вынеси код функций из header в cpp

2023-12-19 09:55 UTC, nekdfl commented on BlessedChat/include/Server.hpp
предлагаю вынести из файла определения функций и оставить только объявления.

2023-12-19 09:55 UTC, nekdfl commented on BlessedChat/include/Server.hpp
> +	void printProperties(const std::string& base)
где вызывается эта функция?

2023-12-19 09:55 UTC, nekdfl commented on BlessedChat/include/Server.hpp
> +#include <Poco/Util/OptionException.h>
надо избегать лишних include в header файлах. Тут должны быть только те, что необходимы для объявлений функций.

2023-12-19 09:55 UTC, nekdfl commented on components/arg_parser/poco_arg_parser.cpp
> +void PocoArgParser::parse()
почему метод пустой? каким методом вызывается парсинг опций командной строки?

2023-12-20 20:27 UTC, blessed2142 commented on components/arg_parser/poco_arg_parser.cpp
> +void PocoArgParser::parse()
ProcessOptions(). Находится под капотом Poco::Util::Application

2023-12-20 20:27 UTC, blessed2142 commented on BlessedChat/include/Server.hpp
> +	void printProperties(const std::string& base)
В мейне

2023-12-20 20:42 UTC, blessed2142 commented on BlessedChat/include/Server.hpp
Сделано.

2023-12-20 20:42 UTC, blessed2142 commented on BlessedChat/include/Server.hpp
> +#include <Poco/Util/OptionException.h>
Убрал один include, но не этот. Этот нужен

2023-12-23 19:44 UTC, nekdfl approved these changes

2023-12-25 07:18 UTC, merged